name: Lint & Formatting
on: [pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install linter and formatter
        run: pip install black flake8
      - name: Run linter
        run: flake8 --ignore=E501,W503
      - name: Run formatter check
        run: black --check .
