name: Test
on: [push, pull_request]
jobs:
  test:
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6.2, 3.7, 3.8, 3.9]
    runs-on: ubuntu-latest
    steps:
      - name: Install ubuntu dependencies
        run: sudo apt-get update && sudo apt-get install libasound2-dev
      - uses: actions/checkout@v2
      - name: Setup python
        uses: gabrielfalcao/pyenv-action@v5
        with:
          default: "${{ matrix.python-version }}"
          command: pip install -U pip
      - name: Setup poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.11
      - name: Install package
        run: poetry install
      - name: Run tests
        run: poetry run pytest
